name: Docker API CI/CD

on:
  push:
    branches:
      - master

jobs:
  docker-api-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4


      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push API image
      - name: Build and push API image
        run: |
          docker build -t luongnguyenminhan/toxicity-api:latest .
          docker push luongnguyenminhan/toxicity-api:latest

      # Test the API service (optional)
      - name: Test API service
        run: |
          docker run -d --name test-api -p 8000:8000 --env ENV=development luongnguyenminhan/toxicity-api:latest
          sleep 30
          docker ps
          docker logs test-api
          docker stop test-api
          docker rm test-api

  deploy:
    needs: docker-api-build
    runs-on: ubuntu-latest
    if: success()

    steps:
      # Deploy to production server (if you have one)
      - name: Deploy to server
        run: |
          echo "Deployment step - configure based on your deployment target"
          echo "Image pushed successfully:"
          echo "- luongnguyenminhan/toxicity-api:latest"